export const C = {
  bg:           '#f5f0eb',
  bgMuted:      '#ede8e2',
  surface:      '#ffffff',
  border:       '#e2d9cf',
  borderStrong: '#c8bdb2',
  ink:          '#1e3a2f',
  inkSoft:      '#4a6358',
  inkMuted:     '#8a9e96',
  primary:      '#1e3a2f',
  primaryHov:   '#162d24',
  accent:       '#fa6b04',
  accentHov:    '#e05f03',
  accentLight:  '#fff3eb',
  accentBorder: '#fdc89a',
  success:      '#2d6a4f',
  successLight: '#e8f4ee',
  successBorder:'#a8d5ba',
  warning:      '#a85c2a',
  warningLight: '#fdf0e8',
  warningBorder:'#e8c4a0',
} as const
