import type { QuoteComparisonInput } from '../comparison/model.js'

export const sampleComparison: QuoteComparisonInput = {
  lines: [
    { id: 'line-doors', description: 'Door hardware set', requestedQuantity: 100, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-frames', description: 'Hollow metal frames', requestedQuantity: 40, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-closers', description: 'Door closers', requestedQuantity: 60, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-locksets', description: 'Classroom locksets', requestedQuantity: 95, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-hinges', description: 'Ball bearing hinges', requestedQuantity: 320, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-panic', description: 'Panic exit devices', requestedQuantity: 18, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-thresholds', description: 'Aluminum thresholds', requestedQuantity: 42, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-weatherstrip', description: 'Weatherstripping sets', requestedQuantity: 240, requestedUnit: 'LF', scope: 'in-scope' },
    { id: 'line-kickplates', description: 'Stainless kick plates', requestedQuantity: 55, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-stops', description: 'Wall stops', requestedQuantity: 110, requestedUnit: 'EA', scope: 'in-scope' },
    { id: 'line-accessories', description: 'Bathroom accessory kits', requestedQuantity: 12, requestedUnit: 'SET', scope: 'in-scope' },
    { id: 'line-keying', description: 'Master keying allowance', requestedQuantity: 1, requestedUnit: 'LS', scope: 'in-scope' },
  ],
  vendorQuotes: [
    {
      vendorId: 'vendor-acme',
      vendorName: 'Acme Supply',
      lines: [
        { vendorId: 'vendor-acme', lineItemId: 'line-doors', unitPrice: 82, quotedQuantity: 100, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-frames', unitPrice: 145, quotedQuantity: 40, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-closers', unitPrice: 61, quotedQuantity: 60, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-locksets', unitPrice: 128, quotedQuantity: 95, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-hinges', unitPrice: 9.5, quotedQuantity: 320, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-panic', unitPrice: 410, quotedQuantity: 18, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-thresholds', unitPrice: 36, quotedQuantity: 42, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-weatherstrip', unitPrice: 5.8, quotedQuantity: 240, quotedUnit: 'LF' },
        { vendorId: 'vendor-acme', lineItemId: 'line-kickplates', unitPrice: 48, quotedQuantity: 55, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-stops', unitPrice: 7.25, quotedQuantity: 110, quotedUnit: 'EA' },
        { vendorId: 'vendor-acme', lineItemId: 'line-accessories', unitPrice: 620, quotedQuantity: 12, quotedUnit: 'SET' },
        { vendorId: 'vendor-acme', lineItemId: 'line-keying', unitPrice: 1850, quotedQuantity: 1, quotedUnit: 'LS' },
      ],
    },
    {
      vendorId: 'vendor-buildpro',
      vendorName: 'BuildPro Materials',
      lines: [
        { vendorId: 'vendor-buildpro', lineItemId: 'line-doors', unitPrice: 74, quotedQuantity: 50, quotedUnit: 'EA', quantityResolution: 'normalized-to-requested' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-frames', noBid: 'explicit' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-closers', unitPrice: 58, quotedQuantity: 60, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-locksets', unitPrice: 121, quotedQuantity: 95, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-hinges', unitPrice: 8.75, quotedQuantity: 320, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-panic', noBid: 'cannot-supply' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-thresholds', unitPrice: 34, quotedQuantity: 42, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-weatherstrip', unitPrice: 5.45, quotedQuantity: 240, quotedUnit: 'LF' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-kickplates', unitPrice: 45, quotedQuantity: 55, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-stops', unitPrice: 6.95, quotedQuantity: 110, quotedUnit: 'EA' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-accessories', unitPrice: 590, quotedQuantity: 12, quotedUnit: 'SET' },
        { vendorId: 'vendor-buildpro', lineItemId: 'line-keying', unitPrice: 2100, quotedQuantity: 1, quotedUnit: 'LS' },
      ],
    },
    {
      vendorId: 'vendor-northstar',
      vendorName: 'Northstar Hardware',
      lines: [
        { vendorId: 'vendor-northstar', lineItemId: 'line-doors', unitPrice: 79, quotedQuantity: 120, quotedUnit: 'EA', quantityResolution: 'accepted-vendor-quantity' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-frames', unitPrice: 152, quotedQuantity: 40, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-closers', noBid: 'missing' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-locksets', unitPrice: 132, quotedQuantity: 95, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-hinges', unitPrice: 9.25, quotedQuantity: 320, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-panic', unitPrice: 395, quotedQuantity: 18, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-thresholds', unitPrice: 39, quotedQuantity: 42, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-weatherstrip', noBid: 'missing' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-kickplates', unitPrice: 47, quotedQuantity: 55, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-stops', unitPrice: 7.5, quotedQuantity: 110, quotedUnit: 'EA' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-accessories', noBid: 'explicit' },
        { vendorId: 'vendor-northstar', lineItemId: 'line-keying', unitPrice: 1750, quotedQuantity: 1, quotedUnit: 'LS' },
      ],
    },
  ],
  selections: [
    { lineItemId: 'line-doors', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-frames', state: 'selected-vendor', vendorId: 'vendor-acme' },
    { lineItemId: 'line-closers', state: 'deferred' },
    { lineItemId: 'line-locksets', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-hinges', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-panic', state: 'selected-vendor', vendorId: 'vendor-northstar' },
    { lineItemId: 'line-thresholds', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-weatherstrip', state: 'selected-vendor', vendorId: 'vendor-acme' },
    { lineItemId: 'line-kickplates', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-stops', state: 'selected-vendor', vendorId: 'vendor-buildpro' },
    { lineItemId: 'line-accessories', state: 'selected-vendor', vendorId: 'vendor-acme' },
    { lineItemId: 'line-keying', state: 'selected-vendor', vendorId: 'vendor-northstar' },
  ],
}
